version = 5.6.0
archive_dir = /etc/letsencrypt/archive/dev.itconnect.pl
cert = /etc/letsencrypt/live/dev.itconnect.pl/cert.pem
privkey = /etc/letsencrypt/live/dev.itconnect.pl/privkey.pem
chain = /etc/letsencrypt/live/dev.itconnect.pl/chain.pem
fullchain = /etc/letsencrypt/live/dev.itconnect.pl/fullchain.pem
[renewalparams]
account = 3e7909993a2bd44f124a9ad1831aa1f8
authenticator = dns-cloudflare
dns_cloudflare_propagation_seconds = 60
dns_cloudflare_credentials = /etc/letsencrypt/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
