<?php
/**
 * FreeCRM - Customer Relationship Management System
 *
 * @project FreeCRM
 * @author bmankowski@gmail.com
 * @copyright (c) FreeCRM
 * @license FreeCRM Public License 1.0
 */

declare(strict_types=1);

namespace App\Field;

/**
 * Resolves vtiger_field.field_kind from legacy metadata (uitype, fieldname, typeofdata).
 * Used by migrations/backfill; runtime reads field_kind from DB once wired (Phase 1b).
 */
final class FieldKind
{
	/** @var array<int, string> */
	private const UITYPE_MAP = [
		3   => 'autogenerated',
		4   => 'recordNumber',
		8   => 'totalTime',
		9   => 'percentage',
		10  => 'reference',
		11  => 'phone',
		13  => 'email',
		15  => 'picklist',
		16  => 'multipicklist',
		17  => 'url',
		26  => 'documentsFolder',
		27  => 'fileLocationType',
		28  => 'documentsFileUpload',
		32  => 'languages',
		33  => 'multipicklist',
		50  => 'reference',
		51  => 'reference',
		52  => 'userCreator',
		53  => 'owner',
		54  => 'multiowner',
		56  => 'boolean',
		57  => 'reference',
		58  => 'reference',
		59  => 'reference',
		61  => 'file',
		66  => 'referenceProcess',
		67  => 'referenceLink',
		68  => 'referenceSubProcess',
		69  => 'image',
		71  => 'currency',
		72  => 'currency',
		73  => 'reference',
		75  => 'reference',
		76  => 'reference',
		80  => 'reference',
		81  => 'reference',
		98  => 'userRole',
		101 => 'reference',
		117 => 'currencyList',
		120 => 'sharedOwner',
		156 => 'boolean',
		301 => 'modules',
		302 => 'tree',
		303 => 'taxes',
		304 => 'inventoryLimit',
		305 => 'multiReferenceValue',
		306 => 'multiReference',
		308 => 'rangeTime',
		309 => 'categoryMultipicklist',
		311 => 'multiImage',
		330 => 'multiAttachmentJson',
		342 => 'recurrence',
		357 => 'reference',
		358 => 'mailSmtpSelect',
		359 => 'modulesMultipicklist',
	];

	/** @var array<int, string> uitype → field_kind when not in UITYPE_MAP and not in vtiger_ws_fieldtype */
	private const UITYPE_FALLBACK = [
		1   => 'string',
		2   => 'string',
		5   => 'date',
		6   => 'date',
		14  => 'time',
		19  => 'text',
		20  => 'text',
		21  => 'text',
		22  => 'text',
		24  => 'text',
		70  => 'datetime',
		85  => 'string',
		255 => 'string',
		300 => 'text',
	];

	/**
	 * @param array<int, string> $webserviceByUitype uitype → vtiger_ws_fieldtype.fieldtype
	 */
	public static function resolve(int $uitype, string $fieldName, string $typeofdata, array $webserviceByUitype): string
	{
		if ($uitype === 55) {
			if ($fieldName === 'salutationtype') {
				return 'picklist';
			}
			if ($fieldName === 'firstname') {
				return 'salutation';
			}
		}

		if (isset(self::UITYPE_MAP[$uitype])) {
			return self::UITYPE_MAP[$uitype];
		}

		if (isset($webserviceByUitype[$uitype])) {
			return $webserviceByUitype[$uitype];
		}

		if (isset(self::UITYPE_FALLBACK[$uitype])) {
			return self::UITYPE_FALLBACK[$uitype];
		}

		return self::fromTypeofdata($typeofdata, $uitype);
	}

	private static function fromTypeofdata(string $typeofdata, int $uitype): string
	{
		$code = FieldDefinition::normalizeTypeofdata($typeofdata);

		return match ($code) {
			'V'     => 'string',
			'M'     => 'text',
			'D'     => 'date',
			'DT'    => 'datetime',
			'T'     => 'time',
			'I'     => 'integer',
			'N'     => in_array($uitype, [71, 72], true) ? 'currency' : 'decimal',
			'NN'    => 'float',
			'C'     => 'boolean',
			'E'     => 'email',
			'P'     => 'password',
			default => throw new \InvalidArgumentException(
				"Cannot resolve field_kind for uitype {$uitype} with typeofdata '{$typeofdata}'"
			),
		};
	}
}
